/**
*   @file EngineShaderTypes.h
 *  @layer Engine
 *  @module Resources
 *  @author CybaricFox
 *  @brief Various structures for shader related resources
 *  @version 1.0
 *  @date 09-11-2026
 *
 *  @copyright (c) 2026
 */

#pragma once

enum ShaderAttributeType {
    SHADER_ATTRIBUTE_TYPE_FLOAT32 = 0U,
    SHADER_ATTRIBUTE_TYPE_FLOAT32_2 = 1U,
    SHADER_ATTRIBUTE_TYPE_FLOAT32_3 = 2U,
    SHADER_ATTRIBUTE_TYPE_FLOAT32_4 = 3U,
    SHADER_ATTRIBUTE_TYPE_MATRIX_4 = 4U,
    SHADER_ATTRIBUTE_TYPE_INT8 = 5U,
    SHADER_ATTRIBUTE_TYPE_UINT8 = 6U,
    SHADER_ATTRIBUTE_TYPE_INT16 = 7U,
    SHADER_ATTRIBUTE_TYPE_UINT16 = 8U,
    SHADER_ATTRIBUTE_TYPE_INT32 = 9U,
    SHADER_ATTRIBUTE_TYPE_UINT32 = 10U,
};

enum ShaderUniformType {
    SHADER_UNIFORM_TYPE_FLOAT32 = 0U,
    SHADER_UNIFORM_TYPE_FLOAT32_2 = 1U,
    SHADER_UNIFORM_TYPE_FLOAT32_3 = 2U,
    SHADER_UNIFORM_TYPE_FLOAT32_4 = 3U,
    SHADER_UNIFORM_TYPE_INT8 = 4U,
    SHADER_UNIFORM_TYPE_UINT8 = 5U,
    SHADER_UNIFORM_TYPE_INT16 = 6U,
    SHADER_UNIFORM_TYPE_UINT16 = 7U,
    SHADER_UNIFORM_TYPE_INT32 = 8U,
    SHADER_UNIFORM_TYPE_UINT32 = 9U,
    SHADER_UNIFORM_TYPE_MATRIX_4 = 10U,
    SHADER_UNIFORM_TYPE_SAMPLER = 11U,
    SHADER_UNIFORM_TYPE_CUSTOM = 255U
};

enum ShaderStage {
    SHADER_STAGE_VERTEX = 0x00000001,
    SHADER_STAGE_GEOMETRY = 0x00000002,
    SHADER_STAGE_FRAGMENT = 0x00000004,
    SHADER_STAGE_COMPUTE = 0x00000008
};

enum ShaderScope {
    SHADER_SCOPE_GLOBAL,
    SHADER_SCOPE_INSTANCE,
    SHADER_SCOPE_LOCAL
};